package wasmcloud:host;

world interfaces {
    import wasi:blobstore/blobstore@0.1.0;
    import wasi:http/outgoing-handler@0.2.0;
    import wasi:keyvalue/atomic@0.1.0;
    import wasi:keyvalue/eventual@0.1.0;

    import wasmcloud:messaging/consumer;
}
